set dotenv-load

RSC_LICENSE := env_var("RSC_LICENSE")
R_VERSION := env_var_or_default("R_VERSION", "4.1.2")
PYTHON_VERSION := env_var_or_default("PYTHON_VERSION", "3.10.4")

# -----------------------------------------------------------------------------
# Build RSC
# -----------------------------------------------------------------------------

# Install RStudio Connect and all of the dependencies
build-rsc: 
    # Basic setup
    sudo apt-get update
    sudo apt-get update
    sudo apt-get install -y gdebi-core

    # Install RSC and required dependencies
    just install-r 
    just symlink-r
    just install-python
    just install-rsc
    just copy-config-files

    # Restart
    sudo systemctl restart rstudio-connect

# -----------------------------------------------------------------------------
# Install
# -----------------------------------------------------------------------------

install-rsc:
    curl -O https://cdn.rstudio.com/connect/2022.07/rstudio-connect_2022.07.0~ubuntu20_amd64.deb
    sudo gdebi -n rstudio-connect_2022.07.0~ubuntu20_amd64.deb
    sudo /opt/rstudio-connect/bin/license-manager activate {{RSC_LICENSE}}

install-r:
    curl -O https://cdn.rstudio.com/r/ubuntu-2004/pkgs/r-{{R_VERSION}}_1_amd64.deb
    sudo gdebi -n r-{{R_VERSION}}_1_amd64.deb

symlink-r:
    sudo ln -s /opt/R/{{R_VERSION}}/bin/R /usr/local/bin/R
    sudo ln -s /opt/R/{{R_VERSION}}/bin/Rscript /usr/local/bin/Rscript

install-python:
    # https://docs.rstudio.com/resources/install-python/
    # install python
    curl -O https://cdn.rstudio.com/python/ubuntu-2004/pkgs/python-{{PYTHON_VERSION}}_1_amd64.deb
    sudo gdebi -n python-{{PYTHON_VERSION}}_1_amd64.deb
    sudo /opt/python/{{PYTHON_VERSION}}/bin/python3 -m pip install --upgrade pip setuptools wheel


copy-config-files:
    sudo cp ~/rstudio-connect.gcfg /etc/rstudio-connect/rstudio-connect.gcfg
